const { Op } = require('sequelize');
const db = require('../db');
const Message = require('./message');

const Conversation = db.define('conversation', {});

/* 
NOTE: method `finConversation` has been removed.
Since User and Conversation have many-to-many relationships 
declared in `index.js`,the conversations related to a user 
can be quired by using `getConversations` method in User instance 
generated by sequelize.
*/

module.exports = Conversation;
